In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [44]:
array_1d = np.arange(1, 11)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [47]:
array_2d = np.random.randint(1, 100, size=(3, 3))
print("\n2D 3x3 Array:\n", array_2d)


2D 3x3 Array:
 [[18 55 88]
 [17 33 58]
 [41 72 55]]


In [ ]:
print("Sum:", array_1d.sum())
print("Mean:", array_1d.mean())
print("Max:", array_1d.max())

In [49]:
array_1d[array_1d > 5] = 0
print(array_1d)

[1 2 3 4 5 0 0 0 0 0]


In [50]:
array_1d = array_1d * 2
print(array_1d)

[ 2  4  6  8 10  0  0  0  0  0]
